### PR TITLE
Added API support to register custom craft.

### PR DESCRIPTION
**Pull request by Skaapdev**
Hi @random-geek 

As per https://github.com/waxtatect/basic_machines/pull/11

I added a small change to allow and API call to register a custom craft.

Thanks

### CODE REVIEW

**Comment by random-geek** [comment]
Thanks. I haven't touched this mod (or played Minetest much) in a long time, but I'll consider this PR.

**Comment by Skaapdev** [comment]
@random-geek  I think it is good now but perhaps hold off until https://github.com/waxtatect/basic_machines/pull/11 is merged. But also let me know if you see something. Thanks!

**Comment by random-geek** [comment]
I forgot that craft recipes used by minetest.register_craft are not structured the same as when they're returned by minetest.get_all_craft_recipes. 🤦

I'm considering implementing the function differently to better match minetest.register_craft, if that affects your other PR.

**Comment by Skaapdev** [comment]
>I forgot that craft recipes used by minetest.register_craft are not structured the same as when they're returned by minetest.get_all_craft_recipes. 🤦

Could that explain some missing recipes? 
I sometimes notice one or two I can't find.  For example I can find `farming:cotton_seed` recipe but not `farming:wheat_seed` and I know for sure digging grass can yield `wheat_seed` in my game.

wheat_seed
cotton_seed

**Comment by random-geek** [comment]
Are you using the latest commit? I think the contentdb release wasn't updated

**Comment by Skaapdev** [comment]
I am using a fork from your repo https://github.com/Skaapdev/cg_plus/commits/master/ so if you latest commit is https://github.com/Skaapdev/cg_plus/commit/ab5d53003c70361467926e04dddec7930bec8d7d then yes.

**Comment by random-geek** [comment]
Which game are you using? This is what shows in MTG for me:

image

**Comment by random-geek** [comment]
See the latest commit for custom craft support. My solution is slightly different, and I changed a few other things as well while I was thinking of it. Please let me know if there are any bugs or issues.

**Comment by Skaapdev** [comment]
@random-geek 

> Which game are you using? This is what shows in MTG for me:

You are correct, that MTG farming works fine for me as well. It looks like it only happens with the particular farming mod I am using: https://codeberg.org/tenplus1/farming.git

EDIT btw, I found the reason is that the grass is somewhere set to be part of `not_in_creative_inventory` group.


>See the latest commit for custom craft support. My solution is slightly different, and I changed a few other things as well while I was thinking of it. Please let me know if there are any bugs or issues.

Thank you! This is great and it works flawlessly. I have updated the [Basic machines PR](https://github.com/waxtatect/basic_machines/pull/11)  to use this implementation now.

**Comment by random-geek** [comment]
> EDIT btw, I found the reason is that the grass is somewhere set to be part of `not_in_creative_inventory` group.

Unfortunately, I can't think of an elegant solution to this problem. I tried enabling digging recipes coming from `not_in_creative_inventory` nodes, and the result is a lot of nonsensical clutter in the crafting guide: the top and bottom portions of beds, all the heights of each `farming` plant that drops a seed, left and right doors...

I could add manual craft registrations for plants in the farming mod, but that feels like a slippery slope into doing the same for every other mod/game.

**Comment by Skaapdev** [comment]
@random-geek 

> I could add manual craft registrations for plants in the farming mod, but that feels like a slippery slope into doing the same for every other mod/game.

The problem lies with the `farming redo` mod in this example. I feel strongly that CGP behaviour is already consistent and correct regarding this. I added some debug lines to filter and see what exactly I am missing that still has drops. The rest  was all clutter as you said. 

```
        if def.description and def.description ~= ""
                and minetest.get_item_group(item, "not_in_creative_inventory") == 0
                and minetest.get_item_group(item, "not_in_craft_guide") == 0 then
            table.insert(cg.items_all.list, item)
            cg.crafts[item] = minetest.get_all_craft_recipes(item) or {}
            table.insert_all(cg.crafts[item], custom_crafts[item] or {})
        --[[
        else  -- debug lines to see if there are missing item drops.
            local blacklist = {"moreblocks", "stair", "slab", "slope", "panel", "micro"}
            local found = false
            for _, blacklistedString in ipairs(blacklist) do
                if string.find(item, blacklistedString) then
                    found = true
                    break
                end
            end
            if not found and def.drop and def.drop ~= "" then
                print("Skipping: " .. dump(item) .. " drop: " .. dump(def.drop))
            end
        --]]    
        end
```


I have already [forked `farming redo` for my fix](https://codeberg.org/Skaapdev/farming/commit/c1c4b72e4295d24d52d63e2635bbb7fd1ade1982). It seems that `default:grass_1` had no `drops` and also happens to be the only node that did not have `not_in_creative_inventory = 1`.  This seems to be the real difference between `farming redo` and `default MTG`. Hope that makes sense. Thank you for your time looking at this!

**Pull request closed without merging**
